apiVersion: v1
kind: Service
metadata:
  name: web-server
  namespace: web-server
spec:
  selector:
    app: web-server
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30090 # This should match the port opened in the KIND config
  type: NodePort