{{- if .Values.webServer.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.namespaces.webServer }}
data:
  nginx.conf: {{ .Values.webServer.nginx.config | quote }}
{{- end }}
