apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: ng-voice-cluster
servers: 1
agents: 2
image: rancher/k3s:v1.31.5-k3s1

ports:
  - port: 30000-30100:30000-30100
    nodeFilters:
      - loadbalancer

options:
  k3d:
    wait: true
    timeout: "120s"
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --node-label=db-node=node-1
        nodeFilters:
          - agent:0
      - arg: --node-label=db-node=node-2
        nodeFilters:
          - agent:1
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
