apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - mysql-ss.yaml
  - mysql-service.yaml
  - netpol.yaml
  - backup-pvc.yaml
  - internal-backup-cronjob.yaml
  - s3-backup.yaml